KAFKA_BROKER_URL = "localhost"
KAFKA_BROKER_PORT = "29092"

KAFKA_SUBS_COUNT_TOPIC = 'subsCount'


KAFKA_CONSUMER_GROUP = "channelService"
DATA_BASE_NAME = ""
DATA_BASE_USER = ""
DATA_BASE_PASS = ""
DATA_BASE_URL = ""
DATA_BASE_PORT = ""
